# See https://jupyterbook.org/customize/config.html
 
# Book settings
title                      : "BIP Labs"
author                     : "Vincent Mazet (University of Strasbourg, France)"
copyright                  : "2020-2026"
#logo                       : figs/logo.png
exclude_patterns            : [ "demo.ipynb" ]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks         : "off"

# HTML-specific settings
html:
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : "" # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  extra_footer              : "Basics of Image Processing &mdash; Vincent Mazet (Université de Strasbourg), 2020-2026 &mdash; <a href='https://vincmazet.github.io/bip/appendices/license.html'>CC BY-NC 4.0</a>."

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname              : image-labs.tex

# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  colab_url                 : ""  # The URL of the Colab
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebelab                  : ""  # Add a thebelab button to pages (requires the repository to run on Binder)

# Information about where the book exists on the web
repository:
  url                       : "" #"https://github.com/vincmazet/bip-labs"  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    language                : en
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js # Pour utiliser plotly